name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/rusted-pacman rusted-pacman
        chmod 777 rusted-pacman
        tar cpfz rusted-pacman_linux_x86_64.tar.gz rusted-pacman

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: rusted-pacman_linux_x86_64.tar.gz

  win_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - name: Prepare artifact
      shell: pwsh
      run: |
        Move-Item target/release/rusted-pacman.exe rusted-pacman.exe
        Compress-Archive -Path rusted-pacman.exe -DestinationPath rusted-pacman_windows_x86_64.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: rusted-pacman_windows_x86_64.zip
